### PR TITLE
Externally maintained third-party platform-specific components

### LINKED ISSUE #15: [UAVCAN/CAN] for Arduino
Following up on my comment [here](https://forum.uavcan.org/t/libcanard-v1-stm32-driver-design-guidelines/798/3) I'm wondering about what's the best way to achieve this? There is currently no top-level `<CAN.h>` in the Arduino environment as there is for UART (`<Serial.h>`), I2C (`<Wire.h>`) and SPI (`<SPI.h>`). However, I could rather quickly donate a working Arduino Library intended for interacting with the (old but popular) `MCP2515` CAN communication chip. But how should the folder structure be set up?
```bash
arduino
|-- libcanard
   |-- arduino (for eventual top-level CAN support?)
   |-- mcp2515
```
What do you think @pavel-kirienko ?

### PR DESCRIPTION
**Pull request by pavel-kirienko**
This is a follow-up to https://github.com/UAVCAN/platform_specific_components/issues/15#issuecomment-702126881.

We need a third opinion so I would like to summon @thirtytwobits and let him choose how do we handle the inclusion of externally maintained third-party drivers:

- link from README like I am proposing here in this PR **[merge this PR if you choose this option]**
- use git-subtree **[reject this PR if you choose this option]**

Thanks.

Fixes #15

### CODE REVIEW

**Comment by aentinger** [comment]
Did you have any chance to take a look at this @thirtytwobits :wave: ?

**Comment by thirtytwobits** [comment]
reading now...

**Comment by thirtytwobits** [comment]
My €0.01, sub-tree is great for stitching together software you strongly own. Submodule works better to keep external software at arm's length. As such, I think we should use all three based on the level of ownership the UAVCAN community is willing to have for a given platform specific component. If we feel it's essential to the success of this standard we may use a subtree to ensure we have a copy of the source in our repos and aren't at risk that the external source will disappear. If we want to encourage the use of the external component but aren't willing to maintain the local subtree then submodules can be used. If we suspect the technology is of interest but do not have the time to vet it or test new revisions when a PR to update the submodule commit is posted then we provide a link in the README.md

**Comment by aentinger** [comment]
Thank you very much for your input @thirtytwobits (and let me add that I think you are selling yourself short, I'd say your statement is worth at least 0.02€ :wink:). You provide an interesting perspective as I've so far only evaluated `git submodule`, `git subtree` etc. under the point of view what would work best from a technical perspective. You are adding a "degree of association with UAVCAN project/support provided by UAVCAN members" dimension to what appears on the surface a simple technical procedure question.

Following your logic I must arrive at the conclusion that [107-Arduino-MCP2515](https://github.com/107-systems/107-Arduino-MCP2515) is certainly not `git subtree` material, but would fit either in the git submodule or link categoy, **depending** how the UAVCAN team judges relevance of the contribution as well as my personal ability and willingness to keep that library supported and working with UAVCAN components.

**Comment by thirtytwobits** [comment]
> Following your logic I must arrive at the conclusion that [107-Arduino-MCP2515](https://github.com/107-systems/107-Arduino-MCP2515) is certainly not `git subtree` material, but would fit either in the git submodule or link category, **depending** how the UAVCAN team judges relevance of the contribution as well as my personal ability and willingness to keep that library supported and working with UAVCAN components.

First, I looked at your project and, how cool! I actually have a Vidor sitting on my desk and haven't found anything fun to do with it but this looks really compelling!

That said, I think this is a link type relationship right now but we can decide to pull it into a submodule as it matures and sees more use and as we mature and see more use thus filling out this repo.

**Comment by aentinger** [comment]
Hi @thirtytwobits :wave: I'm glad you like our [Viper Quadcopter](https://github.com/107-systems/107-Arduino-Viper) project :wink: I believe the `MKR VIDOR 4000` is one seriously underappreciated piece of hardware and have therefore set out to rectify that perception. I'm publishing a very irregular newsletter (newsletter publishing rate varies between 3 weeks to 3 months) on the status of the project (may also contain flame against ineptitude of certain sensor vendors). Do you want to be added to the list?

Getting back to the topic at hand, I'm fine with a link relationship for now. Ultimately I believe that **Arduino** as a platform is valueable to be part of the wider UAVCAN ecosystem because it removes the high entry barrier typically associated with embedded systems development.

**Comment by aentinger** [comment]
Hi :wave: :coffee: I do realise that you guys probably have bigger fish to fry then this tiny PR. But it seems to me that we have a consensus here on merging this as a link and I kindly ask either @pavel-kirienko or @thirtytwobits to merge this PR.

**Pull request merged**
